baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

#tipo

[params.homeInfoParams]
Title = "Oi. 🎍"
Content = "Sou um **estudante**, nessa era da informação, quero condensar o *pouco* que tenho nesse **blog**"

#menus

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30
